[package]
org = "hinduja"
name = "EmployeeApp"
version = "0.1.0"

[build-options]
observabilityIncluded = true

[[platform.java11.dependency]]
artifactId = "mysql-connector-java"
version = "8.0.23"
path = "<path_to_mysql_connector>"
groupId = "mysql"
